package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class HashEquiJoin extends Operator {

    private static final long serialVersionUID = 1L;
    private DbIterator child1;
    private DbIterator child2;
    private JoinPredicate p;
    transient private Tuple t1;
    transient private Tuple t2;
    private TupleDesc mergedTd;

    HashMap<Object,ArrayList<Tuple>> map = new HashMap<>();
    public static final int MAP_SIZE = 40000;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     *
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public HashEquiJoin(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        mergedTd = TupleDesc.merge(child1.getTupleDesc(),child2.getTupleDesc());
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(),child2.getTupleDesc());
    }
    
    public String getJoinField1Name()
    {
        // some code goes here
	return child1.getTupleDesc().getFieldName(p.getField1());
    }

    public String getJoinField2Name()
    {
        // some code goes here
        return child2.getTupleDesc().getFieldName(p.getField2());
    }
    
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open();
        child2.open();
        initMap();
    }

    public void close() {
        // some code goes here
        super.close();
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
    }

    transient Iterator<Tuple> listIt = null;

    public boolean initMap() throws DbException, TransactionAbortedException{
        int count = 0;
        map.clear();
        while (child1.hasNext()){
            t1 = child1.next();
            ArrayList<Tuple> list = map.get(t1.getField(p.getField1()));
            if (list == null){
                list = new ArrayList<>();
                map.put(t1.getField(p.getField1()),list);
            }
            list.add(t1);
            if (count++== MAP_SIZE)
                return true;
        }
        return count > 0;
    }

    public Tuple processList(){
        Tuple mergedT = new Tuple(mergedTd);
        t1 = listIt.next();

        if (mergedT.fieldList.addAll(t1.fieldList) && mergedT.fieldList.addAll(t2.fieldList))
            return mergedT;
        return null;
    }
    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, there will be two copies of the join attribute in
     * the results. (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if (listIt != null && listIt.hasNext()){
            return processList();
        }
        while (child2.hasNext()){
           t2 = child2.next();
           ArrayList<Tuple> l = map.get(t2.getField(p.getField2()));
           if (l == null){
               continue;
           }
           listIt = l.iterator();
           return processList();

        }
        child2.rewind();
        if (initMap()){
            fetchNext();
        }

        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        DbIterator[] children = new DbIterator[2];
        children[0] = child1;
        children[1] = child2;
        return children;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        child1 = children[0];
        child2 = children[1];
    }
    
}
